### Numpy

1 - Utilize o método numpy.info para obter informações do método numpy.add.

In [1]:
# Insira a resposta abaixo.
import numpy as np
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

2 - Utilize a função *range* do python para criar automaticamente uma lista de números variando de 0 até 15. 

In [2]:
# Insira a resposta abaixo.
list = range(0,16)
list

range(0, 16)

3 - Converta a lista criada para um objeto do tipo numpy array.

In [3]:
# Insira a resposta abaixo.
list_array = np.array(list)
list_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

4 - Crie um  novo array equivalente ao anterior utilizando diretamente os recursos do numpy.

In [4]:
# Insira a resposta abaixo.
list_numpy = np.arange(16)
list_numpy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

5 - Utilize o array criado anteriormente para exibir o tipo de dado antes e após convertê-lo para um tipo float. Em seguida, converta novamente o array para um tipo de dado inteiro de 32 bits e exiba o tipo numérico  atual.

In [5]:
# Insira a resposta abaixo.
print(list_numpy.dtype)
list_numpy.dtype = 'float'
print(list_numpy.dtype)
list_numpy.dtype = 'int32'
print(list_numpy.dtype)


int32
float64
int32


6 - A partir do último array utilizado anteriormente, realize os seguintes procedimentos:

1. Exiba o formato atual do array.
2. Altere o formato para (4, 4).
3. Exiba novamente o formato do array após redimensioná-lo.

In [6]:
# Insira a resposta abaixo.
list_numpy = np.arange(16)
# Passo 1 
print(list_numpy.shape)
# Passo 2
list_numpy = list_numpy.reshape((4,4))
# Passo 3
print(list_numpy.shape)

(16,)
(4, 4)


7 - Compute a média, mediana e o desvio padrão do array resultante da questão anterior.

In [7]:
# Insira a resposta abaixo.
print('Média:' + str(list_numpy.mean()))
print('Mediana:' + str(np.median(list_numpy)))
print('Desvio padrão:' + str(list_numpy.std()))

Média:7.5
Mediana:7.5
Desvio padrão:4.6097722286464435


8 - Crie uma cópia do array atual  e transforme todos os números em valores negativos.

In [8]:
# Insira a resposta abaixo.
list_numpy_copy = list_numpy.copy()
list_numpy_copy = np.negative(list_numpy_copy)
list_numpy_copy

array([[  0,  -1,  -2,  -3],
       [ -4,  -5,  -6,  -7],
       [ -8,  -9, -10, -11],
       [-12, -13, -14, -15]])

9 - Realize os seguintes procedimentos:
1. Concatene verticalmente (*row-wise*) o array de números positivos com o array de números negativos.
2.  Concatene horizontalmente (*column-wise*) o array resultante do passo 1 com ele mesmo. 
3. Concatene em profundidade três cópias do array resultante do passo anterior, exibindo o formato final.

In [9]:
# Insira a resposta abaixo.

# Passo 1
vstack_list = np.vstack((list_numpy,list_numpy_copy))
print(vstack_list)
print('\n\n\n')
# Passo 2
hstack_list = np.hstack((vstack_list,vstack_list))
print(hstack_list)
print('\n\n\n')
# Passo 3
dstack_list = np.dstack((hstack_list,hstack_list,hstack_list))
print(dstack_list)

[[  0   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]
 [  0  -1  -2  -3]
 [ -4  -5  -6  -7]
 [ -8  -9 -10 -11]
 [-12 -13 -14 -15]]




[[  0   1   2   3   0   1   2   3]
 [  4   5   6   7   4   5   6   7]
 [  8   9  10  11   8   9  10  11]
 [ 12  13  14  15  12  13  14  15]
 [  0  -1  -2  -3   0  -1  -2  -3]
 [ -4  -5  -6  -7  -4  -5  -6  -7]
 [ -8  -9 -10 -11  -8  -9 -10 -11]
 [-12 -13 -14 -15 -12 -13 -14 -15]]




[[[  0   0   0]
  [  1   1   1]
  [  2   2   2]
  [  3   3   3]
  [  0   0   0]
  [  1   1   1]
  [  2   2   2]
  [  3   3   3]]

 [[  4   4   4]
  [  5   5   5]
  [  6   6   6]
  [  7   7   7]
  [  4   4   4]
  [  5   5   5]
  [  6   6   6]
  [  7   7   7]]

 [[  8   8   8]
  [  9   9   9]
  [ 10  10  10]
  [ 11  11  11]
  [  8   8   8]
  [  9   9   9]
  [ 10  10  10]
  [ 11  11  11]]

 [[ 12  12  12]
  [ 13  13  13]
  [ 14  14  14]
  [ 15  15  15]
  [ 12  12  12]
  [ 13  13  13]
  [ 14  14  14]
  [ 15  15  15]]

 [[  0   0   0]
  [ -1  -1  -1]
  [ -2

10 - Utilize o array do passo 1 da questão anterior e transforme os valores da segunda e terceira colunas em 1.

In [10]:
# Insira a resposta abaixo.
vstack_list[:,1:3] = 1
print(vstack_list)

[[  0   1   1   3]
 [  4   1   1   7]
 [  8   1   1  11]
 [ 12   1   1  15]
 [  0   1   1  -3]
 [ -4   1   1  -7]
 [ -8   1   1 -11]
 [-12   1   1 -15]]


11 - Adicione 2.5 a todos os valores presentes no array resultante da etapa anterior.

In [11]:
# Insira a resposta abaixo.
vstack_list = np.add(vstack_list,2.5)
vstack_list

array([[  2.5,   3.5,   3.5,   5.5],
       [  6.5,   3.5,   3.5,   9.5],
       [ 10.5,   3.5,   3.5,  13.5],
       [ 14.5,   3.5,   3.5,  17.5],
       [  2.5,   3.5,   3.5,  -0.5],
       [ -1.5,   3.5,   3.5,  -4.5],
       [ -5.5,   3.5,   3.5,  -8.5],
       [ -9.5,   3.5,   3.5, -12.5]])

12 - Apresente uma contagem dos valores únicos que estão presentes no array criado na questão anterior. 
 
 Siga o seguinte template: "Quantidade de ocorrências do elemento {}: {}"

In [12]:
# Insira a resposta abaixo.
import numpy as np
np.info(np.unique)

unique, counts = np.unique(vstack_list, return_counts=True)
for i in range(unique.size):
  print("Quantidade de ocorrências do elemento {}: {}".format(unique[i],counts[i]))


 unique(ar, return_index=False, return_inverse=False, return_counts=False,
        axis=None)

Find the unique elements of an array.

Returns the sorted unique elements of an array. There are three optional
outputs in addition to the unique elements:

* the indices of the input array that give the unique values
* the indices of the unique array that reconstruct the input array
* the number of times each unique value comes up in the input array

Parameters
----------
ar : array_like
    Input array. Unless `axis` is specified, this will be flattened if it
    is not already 1-D.
return_index : bool, optional
    If True, also return the indices of `ar` (along the specified axis,
    if provided, or in the flattened array) that result in the unique array.
return_inverse : bool, optional
    If True, also return the indices of the unique array (for the specified
    axis, if provided) that can be used to reconstruct `ar`.
return_counts : bool, optional
    If True, also return the number 

13 - Realize as seguintes operações:
1. Crie uma matriz com valor 3 em todas as posições com dimensionalidade (4, 2).
2. Crie uma matriz identidade de dimensionalidade (4, 4).
3. Compute o produto entre a transposta da primeira matriz e a matriz identidade, apresentando o resultado final.

In [13]:
# Insira a resposta abaixo.

# Passo 1
array = np.zeros((4,2))
array = np.add(array,3)
print(array)

# Passo 2
identidade = np.eye(4)
print(identidade)

# Passo 3
produto = np.dot(array.T, identidade)
print(produto)


[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]]


14 - Realize as seguintes operações:
1. Crie uma nova matriz de valores inteiros de 25 até 49 com dimensionalidade (5,5).
2. Crie uma nova matriz com valores uniformemente espaçados entre 0 e 1 e defina a sua dimensionalidade em (5,1).
3. Concatene horizontalmente as duas matrizes criadas anteriormente.

In [14]:
# Insira a resposta abaixo.

# Passo 1
array = np.arange(25,50)
array = np.reshape(array,(5,5))
print(array)

# Passo 2
array_2 = np.linspace(0,1,5)
array_2 = np.reshape(array_2,(5,1))
print(array_2)

# Passo 3
array_stack = np.hstack((array,array_2))
print(array_stack)

[[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]
[[25.   26.   27.   28.   29.    0.  ]
 [30.   31.   32.   33.   34.    0.25]
 [35.   36.   37.   38.   39.    0.5 ]
 [40.   41.   42.   43.   44.    0.75]
 [45.   46.   47.   48.   49.    1.  ]]


15 - Crie uma nova matriz com dimensionalidade (5,1) com números uniformemente espaçados utilizando um espaço logarítmico ao invés de um espaço linear. 

In [15]:
# Insira a resposta abaixo.
array_log = np.logspace(0,1,5)
array_log = np.reshape(array_log,(5,1))
array_log

array([[ 1.        ],
       [ 1.77827941],
       [ 3.16227766],
       [ 5.62341325],
       [10.        ]])

16 - Crie uma função que receba um array e adicione uma borda composta de zeros nos quatro lados do array. Utilize o array resultante da questão anterior para testar o método criado. 

In [16]:
# Insira a resposta abaixo.
def add_borders(array):
  new_array = np.zeros((array.shape[0]+1,1))
  array = np.concatenate((np.zeros((1,array.shape[1])),array))
  array = np.hstack((new_array,array))
  h_zeros = np.zeros((array.shape[0],1))
  array = np.hstack((array,h_zeros))
  v_zeros = np.zeros((1,array.shape[1]))
  array = np.vstack((array,v_zeros))
  return array

print(add_borders(array_log))

[[ 0.          0.          0.        ]
 [ 0.          1.          0.        ]
 [ 0.          1.77827941  0.        ]
 [ 0.          3.16227766  0.        ]
 [ 0.          5.62341325  0.        ]
 [ 0.         10.          0.        ]
 [ 0.          0.          0.        ]]


17 - Crie um array de 36 números aleatórios oriundos de uma distribuição normal. Exiba o valor máximo, mínimo, a média e o desvio padrão desse array.

In [17]:
# Insira a resposta abaixo.
array = np.random.choice(100,36)
print('Mínimo:' + str(array.argmax()))
print('Máximo:' + str(array.argmin()))
print('Média:' + str(array.mean()))
print('Desvio padrão:' + str(array.std()))

Mínimo:7
Máximo:4
Média:51.27777777777778
Desvio padrão:31.117707633999355


18 - Crie uma matriz de dimensões (50,50) com valores aleatórios entre 0 e 1 (distribuição uniforme). Exiba as duas últimas linhas da matriz.


In [18]:
# Insira a resposta abaixo.
random_array = np.random.random((50,50))
print(random_array[random_array.shape[0] - 2 : random_array.shape[0] , ])

[[0.56403569 0.12896976 0.34318692 0.20720518 0.11733365 0.00720234
  0.46079163 0.51181438 0.79980579 0.38807596 0.702487   0.4658953
  0.43313891 0.72359776 0.47149854 0.9674666  0.84210807 0.74923697
  0.70068074 0.66311292 0.74633585 0.57377788 0.65002266 0.52981593
  0.6017803  0.75752643 0.45472516 0.51957044 0.50024454 0.02634958
  0.66888191 0.53657096 0.20328414 0.61826846 0.69448751 0.84437436
  0.389202   0.521122   0.58958385 0.80857554 0.10769947 0.42562605
  0.05472335 0.14069159 0.20473427 0.93942841 0.31496752 0.34111024
  0.55509644 0.33299889]
 [0.51942752 0.47272256 0.92622615 0.69990827 0.00374288 0.06963967
  0.94779791 0.03045197 0.38835602 0.84760123 0.44387538 0.90554832
  0.12447032 0.38338433 0.19926638 0.0094483  0.52364159 0.38293043
  0.78797117 0.02422482 0.35779733 0.3211538  0.83963521 0.85203432
  0.60443926 0.07621424 0.02718948 0.41060247 0.3577164  0.7542973
  0.08950446 0.70369425 0.85732367 0.82011958 0.28403092 0.60781293
  0.11891556 0.71469344 0

19 - Utilize o array de números aleatórios anterior e apresenta a soma de cada coluna. Em seguida, apresente a soma de cada linha.

In [19]:
# Insira a reposta abaixo.
print(np.sum(random_array,axis=1))
print(np.sum(random_array,axis=0))

[21.97352508 25.75510463 24.65009068 25.16758881 27.22248162 25.19060553
 27.37622122 25.58815466 24.73573349 21.69324959 25.07283148 26.32487494
 26.91902644 25.61626804 24.67239709 22.8349182  25.90818561 24.14535408
 26.35575217 26.72387206 25.74602074 23.4942776  23.84495457 23.58295491
 23.81658509 18.7464245  25.09461177 27.20148426 27.27318592 25.37019455
 20.64191526 28.92066099 27.73489965 26.96912606 24.15971547 24.49988885
 21.43487072 25.06554892 21.44919112 25.03529013 25.82171146 23.08244234
 27.13164778 23.94903118 24.57930226 26.21061585 20.09727151 26.86654968
 24.89921983 23.63191728]
[24.00775842 25.08531311 19.35008306 21.65384677 26.40127758 26.34622661
 25.21541933 27.93207922 25.5232121  23.97617379 25.77643016 23.2895528
 26.81510133 25.50031776 25.22070418 25.34525262 27.35295203 26.03768091
 24.65268526 23.71506469 23.75875655 21.61087151 22.21883288 31.32434977
 24.0110963  22.67931685 21.81498844 25.87112788 26.24777845 21.92339129
 25.40400599 24.25061336 2

20 - Escreve uma função que receba um array como entrada e uma probabilidade *p* entre 0 e 1.  Existe uma probabilidade *p* de que a função retorne o logaritmo do array, caso contrário o array original deve ser retornado. Teste a função utilizando o array da questão anterior. Dica: considere utilizar a biblioteca random do numpy.

In [20]:
# Insira a resposta abaixo.
def func(array,p):
  if p > np.random.random(1)[0]:
    log_array = np.log(array)
    return log_array
  else:
    return array


print(func(random_array,np.random.random(1)[0]))

[[-2.4472382  -0.09258695 -1.49064546 ... -0.05945727 -0.96522219
  -3.10582382]
 [-2.52692649 -0.59876152 -0.06416622 ... -0.36351995 -1.99254731
  -5.88870536]
 [-2.19744973 -0.44463362 -1.9511446  ... -1.33817359 -0.85565239
  -1.10010477]
 ...
 [-0.46453851 -3.04586244 -0.04011742 ... -0.54391433 -0.48138132
  -0.55184316]
 [-0.57263776 -2.04817732 -1.06948002 ... -1.07554958 -0.58861342
  -1.09961613]
 [-0.65502801 -0.74924662 -0.07663685 ... -0.03328022 -0.76946313
  -0.03628717]]


21 - Crie dois arrays de 30 elementos contendo números aleatórios entre 1 e 3. Utilize os dois arrays  para derivar um novo array contendo uma comparação entre os valores de forma a indicar True caso elementos em uma mesma posição apresentam o mesmo valor e False caso contrário. Dica: não é necessário utilizar uma estrutura de repetição.

Exemplo.:

*inputs*:

array([1,3,2])

array([1,2,2])

*output*:

array([True, False, True])

In [21]:
# Insira a resposta abaixo.
array_1 =  np.random.randint(1,4,30)
array_2 = np.random.randint(1,4,30)
array_comparacao = array_1 == array_2
array_comparacao

array([False,  True,  True,  True, False,  True, False, False, False,
       False, False, False, False,  True, False,  True, False,  True,
       False, False, False, False, False, False, False,  True, False,
        True, False,  True])

22 - Compare os dois arrays acima de forma a retornar de uma única só vez um valor booleando indicando se todos os valores contidos em ambos os objetos são iguais.

In [22]:
# Insira a resposta abaixo.
comparacao = np.array_equal(array_1,array_2)
comparacao

False

23 - Realize os seguintes procedimentos:

1. Crie um array com formato 5x5 contendo somente valores verdadeiros. 
2. Dado que se conhece o número de linhas e colunas do array, selecione aleatoriamente trẽs coordenadas (pode haver repetição de coordenadas) e as transforme em False.
3. Crie um array de dimensionalidade 5x5 a partir de um intervalo com valores de 0 até 24.
4. Utilize o array booleano para indexar o array criado no passo anterior.

In [23]:
# Insira a resposta abaixo.

# Passo 1
array_true = np.ones((5,5),dtype='bool')
print(array_true)

# Passo 2
for i in range(3):
  array_true[np.random.randint(0,5),np.random.randint(0,5)] = False
print(array_true)

# Passo 3
array_nums = np.arange(0,25)
array_nums = np.reshape(array_nums,(5,5))
print(array_nums)
# Passo 4

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[[ True  True  True  True  True]
 [ True  True  True False  True]
 [ True  True False  True  True]
 [ True  True  True  True  True]
 [ True  True  True False  True]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
