### Numpy

1 - Utilize o método numpy.info para obter informações do método numpy.add.

In [1]:
import numpy as np


In [2]:
# Insira a resposta abaixo.
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

2 - Utilize a função *range* do python para criar automaticamente uma lista de números variando de 0 até 15. 

In [8]:
# Insira a resposta abaixo.
result = list(range(16))
print(result)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


3 - Converta a lista criada para um objeto do tipo numpy array.

In [9]:
# Insira a resposta abaixo.
result = np.array(result)
print(result)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


4 - Crie um  novo array equivalente ao anterior utilizando diretamente os recursos do numpy.

In [15]:
# Insira a resposta abaixo.
result = np.linspace(0,15,16,dtype=int)
print(result)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


5 - Utilize o array criado anteriormente para exibir o tipo de dado antes e após convertê-lo para um tipo float. Em seguida, converta novamente o array para um tipo de dado inteiro de 32 bits e exiba o tipo numérico  atual.

In [16]:
# Insira a resposta abaixo.

#int64
print(result.dtype)

#conversão
result = result.astype('float64') 

#float64
print(result.dtype)

#conversao
result = result.astype('int32') 

#int32
print(result.dtype)

int32
float64
int32


6 - A partir do último array utilizado anteriormente, realize os seguintes procedimentos:

1. Exiba o formato atual do array.
2. Altere o formato para (4, 4).
3. Exiba novamente o formato do array após redimensioná-lo.

In [17]:
# Insira a resposta abaixo.

# Passo 1 
print(result.shape)
# Passo 2
result = result.reshape(4,4)
# Passo 3
print(result.shape)

(16,)
(4, 4)


7 - Compute a média, mediana e o desvio padrão do array resultante da questão anterior.

In [18]:
# Insira a resposta abaixo.
print(np.mean(result))
print(np.median(result))
print(np.std(result))

7.5
7.5
4.6097722286464435


8 - Crie uma cópia do array atual  e transforme todos os números em valores negativos.

In [24]:
# Insira a resposta abaixo.
NewResult = result.copy()
NewResult = NewResult*-1
NewResult

array([[  0,  -1,  -2,  -3],
       [ -4,  -5,  -6,  -7],
       [ -8,  -9, -10, -11],
       [-12, -13, -14, -15]])

9 - Realize os seguintes procedimentos:
1. Concatene verticalmente (*row-wise*) o array de números positivos com o array de números negativos.
2.  Concatene horizontalmente (*column-wise*) o array resultante do passo 1 com ele mesmo. 
3. Concatene em profundidade três cópias do array resultante do passo anterior, exibindo o formato final.

In [25]:
# Insira a resposta abaixo.

# Passo 1
result2 = np.vstack((result,NewResult))
print(np.shape(result2))


# Passo 2
result3 = np.hstack((result2,result2))
print(np.shape(result3))


# Passo 3
result4 = np.stack((result3,result3,result3))
print(np.shape(result4))

(8, 4)
(8, 8)
(3, 8, 8)


10 - Utilize o array do passo 1 da questão anterior e transforme os valores da segunda e terceira colunas em 1.

In [27]:
# Insira a resposta abaixo.
result2[:,1:3] = 1
print(result2)

[[  0   1   1   3]
 [  4   1   1   7]
 [  8   1   1  11]
 [ 12   1   1  15]
 [  0   1   1  -3]
 [ -4   1   1  -7]
 [ -8   1   1 -11]
 [-12   1   1 -15]]


11 - Adicione 2.5 a todos os valores presentes no array resultante da etapa anterior.

In [28]:
# Insira a resposta abaixo.
result2 = result2 + 2.5
print(result2)

[[  2.5   3.5   3.5   5.5]
 [  6.5   3.5   3.5   9.5]
 [ 10.5   3.5   3.5  13.5]
 [ 14.5   3.5   3.5  17.5]
 [  2.5   3.5   3.5  -0.5]
 [ -1.5   3.5   3.5  -4.5]
 [ -5.5   3.5   3.5  -8.5]
 [ -9.5   3.5   3.5 -12.5]]


12 - Apresente uma contagem dos valores únicos que estão presentes no array criado na questão anterior. 
 
 Siga o seguinte template: "Quantidade de ocorrências do elemento {}: {}"

In [29]:
# Insira a resposta abaixo.

contador = list(np.unique(result2, return_counts=True))

for element in range(len(contador[0])):
  print("Quantidade de ocorrências do elemento {}: {}".format(contador[0][element],contador[1][element]))


Quantidade de ocorrências do elemento -12.5: 1
Quantidade de ocorrências do elemento -9.5: 1
Quantidade de ocorrências do elemento -8.5: 1
Quantidade de ocorrências do elemento -5.5: 1
Quantidade de ocorrências do elemento -4.5: 1
Quantidade de ocorrências do elemento -1.5: 1
Quantidade de ocorrências do elemento -0.5: 1
Quantidade de ocorrências do elemento 2.5: 2
Quantidade de ocorrências do elemento 3.5: 16
Quantidade de ocorrências do elemento 5.5: 1
Quantidade de ocorrências do elemento 6.5: 1
Quantidade de ocorrências do elemento 9.5: 1
Quantidade de ocorrências do elemento 10.5: 1
Quantidade de ocorrências do elemento 13.5: 1
Quantidade de ocorrências do elemento 14.5: 1
Quantidade de ocorrências do elemento 17.5: 1


13 - Realize as seguintes operações:
1. Crie uma matriz com valor 3 em todas as posições com dimensionalidade (4, 2).
2. Crie uma matriz identidade de dimensionalidade (4, 4).
3. Compute o produto entre a transposta da primeira matriz e a matriz identidade, apresentando o resultado final.

In [31]:
# Insira a resposta abaixo.

# Passo 1
r1 = np.ones((4,2))*3
# print(a)
# Passo 2
r2 = np.eye(4)
# print(b)
# Passo 3
r3 = np.dot(r1.T,r2)
print(r3)

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]]


14 - Realize as seguintes operações:
1. Crie uma nova matriz de valores inteiros de 25 até 49 com dimensionalidade (5,5).
2. Crie uma nova matriz com valores uniformemente espaçados entre 0 e 1 e defina a sua dimensionalidade em (5,1).
3. Concatene horizontalmente as duas matrizes criadas anteriormente.

In [36]:
# Insira a resposta abaixo.
# Passo 1
r1 = list(range(25,50))
r1 = np.array(r1).reshape(5,5)

# Passo 2
r2 = np.array(np.linspace(0,1,5)).reshape(5,1)

# Passo 3
r3 = np.hstack((r1 , r2))
print(r3)

[[25.   26.   27.   28.   29.    0.  ]
 [30.   31.   32.   33.   34.    0.25]
 [35.   36.   37.   38.   39.    0.5 ]
 [40.   41.   42.   43.   44.    0.75]
 [45.   46.   47.   48.   49.    1.  ]]


15 - Crie uma nova matriz com dimensionalidade (5,1) com números uniformemente espaçados utilizando um espaço logarítmico ao invés de um espaço linear. 

In [37]:
# Insira a resposta abaixo.
result = np.array(np.logspace(0,1,5)).reshape(5,1)
print(result)

[[ 1.        ]
 [ 1.77827941]
 [ 3.16227766]
 [ 5.62341325]
 [10.        ]]


16 - Crie uma função que receba um array e adicione uma borda composta de zeros nos quatro lados do array. Utilize o array resultante da questão anterior para testar o método criado. 

In [42]:
# Insira a resposta abaixo.
def bordaZeros(array):
  linha, coluna = np.shape(array)
  a = np.zeros(linha+2).reshape((linha+2,1))
  b = np.zeros(coluna)
  c = np.vstack((b,array,b))
  c = np.hstack((a,c,a))
  return c

array = bordaZeros(result)
print(array)

[[ 0.          0.          0.        ]
 [ 0.          1.          0.        ]
 [ 0.          1.77827941  0.        ]
 [ 0.          3.16227766  0.        ]
 [ 0.          5.62341325  0.        ]
 [ 0.         10.          0.        ]
 [ 0.          0.          0.        ]]


17 - Crie um array de 36 números aleatórios oriundos de uma distribuição normal. Exiba o valor máximo, mínimo, a média e o desvio padrão desse array.

In [43]:
# Insira a resposta abaixo.
array36 = np.random.randn(36)

print(array36)

print(np.max(array36))

print(np.min(array36))

print(np.mean(array36))

print(np.std(array36))

[ 0.63158617  0.96198484 -1.0007282   0.21235347 -2.25927631  0.27183081
  0.45207378  1.62366452 -0.33570206  0.02962207 -0.13697451  0.75688981
 -1.2230027  -0.43186471 -1.07143011 -0.87918718 -0.70380906  0.85575031
  0.17515803  0.39827831  1.12176432  0.73652773 -0.93147906 -0.37211824
 -0.30821323  0.65525103 -2.00776713 -0.0739101   0.38214232 -0.49833133
  0.86602114 -1.02216918 -0.03798666 -1.03137778  0.55517166  1.42071734]
1.6236645221768515
-2.259276308591009
-0.061626108331644947
0.8964017600142635


18 - Crie uma matriz de dimensões (50,50) com valores aleatórios entre 0 e 1 (distribuição uniforme). Exiba as duas últimas linhas da matriz.


In [46]:
# Insira a resposta abaixo.
matriz50 = np.random.normal(size=50*50)
matriz50 = matriz50.reshape((50,50))
print(matriz50[-2:])

[[ 0.97628298  2.59830892 -0.2213427  -0.95835251 -1.65846219 -1.06463264
   0.12559318  1.35086682  0.32096175  1.00467462 -1.12095493  0.43396271
   2.42131577  0.16146121 -0.22715118 -0.80200763  0.54549198 -0.00550069
   0.08407323 -0.53026959  0.82226072  0.15639497 -0.26901185  0.17750832
  -0.5076585  -0.30723174  1.09889149 -1.85799375  0.24186573  0.78145567
  -1.15508501 -1.21858995  0.15266128  0.73394525  1.35264274  0.36285398
  -0.62139899 -1.27156772  1.26238747  0.38616315  0.19996896  2.75700191
  -0.05572879  1.32542434 -1.77280079  0.98060595 -1.19051278 -0.07842822
   2.30497025  1.8265061 ]
 [-1.37144262 -1.23918213  1.31067399  1.02690092 -0.50571242  0.46635362
   0.86358999  0.18017898  1.28715467  0.83913747  0.77076008  0.49651384
   0.85991721  0.66294805 -0.5913271   0.22759916  0.60803427 -1.00014311
  -0.44791806 -0.35310495  0.26329223  0.55046068  0.49313059 -0.5529045
  -1.49496731 -0.77844681  1.19090722 -0.9485041   0.02383094  0.84306749
  -0.0200879

19 - Utilize o array de números aleatórios anterior e apresenta a soma de cada coluna. Em seguida, apresente a soma de cada linha.

In [47]:
# Insira a reposta abaixo.
for i in range(np.shape(matriz50)[1]):
  print(np.sum(matriz50[:,i]))

-16.884876208101925
3.537295527784801
-0.032660183825403255
11.828115998746956
9.671433069952261
-2.327210308852239
4.233631292995204
-17.4903066378982
-4.145309762131462
-5.382766907096664
11.156068407235354
-1.7753638754189607
-2.6883145147548775
-6.696047413036801
-1.9356135478043928
-9.275587531020737
4.874019400609314
7.712167298747717
6.138312697899272
-10.145458412798934
-10.172171337954056
5.515247208265578
14.301622767107604
4.985638225413654
-1.7629104111865508
1.4447617299918267
-1.0774264285182293
-0.9717243567113586
4.3349701606285
1.328540948955085
10.413170357182532
-13.080204530542762
-5.789996111338443
-11.513811103109377
10.946057847460033
0.07800918701623749
-17.15998046718884
2.450718887176251
-14.775158181124553
5.359687470429452
11.683260191584893
-6.178638815698974
-3.8459734524057034
-13.351800292070447
5.003949860592075
2.3448552397944997
10.976988499722614
-0.2339944331528323
-5.566765372451552
6.206294148667408


In [51]:
for i in range(np.shape(matriz50)[0]):
  print(np.sum(matriz50[i,:]))

-2.85232199505591
-2.031127778084529
0.8806355931488365
14.30476052377656
-2.55384144109847
4.909645828532158
-9.466124865223014
-15.282704146098077
3.5539574457918235
6.434517779353337
-9.861444620425669
3.947788228328105
0.5659495184832444
-9.273043867291708
-0.8787498869190089
1.383402053596793
1.9043238817097712
-12.007761673683103
-7.520032646366329
-2.587831565622321
8.114316597529283
4.494809244119508
0.28212231040227664
-2.8752777036312405
-10.382436694103525
-12.83826846991817
5.225612746275143
-0.1754760976579382
7.18608837068293
8.557184297348446
2.3779696021267096
-4.161190582896664
4.911705765246915
-6.6543073914772295
-5.66869710214384
0.6946915948278247
4.542431319424173
7.663677162508236
-12.229165938775013
-4.440973380849023
-7.799541263062137
0.359635024111832
1.1182278917961375
7.597222283135819
-1.0576795161723513
-11.355341590553593
4.437331783518403
9.874242906292162
10.051819312982978
0.8440169798243035


20 - Escreve uma função que receba um array como entrada e uma probabilidade *p* entre 0 e 1.  Existe uma probabilidade *p* de que a função retorne o logaritmo do array, caso contrário o array original deve ser retornado. Teste a função utilizando o array da questão anterior. Dica: considere utilizar a biblioteca random do numpy.

In [53]:
# Insira a resposta abaixo.
def probabilidade(array, probabilidade):
  if probabilidade <= 1 and probabilidade >= 0:
    rand = np.random.random()
    if rand <= probabilidade: return np.log(array)
    else: return matriz50

  else:
    return 'Por favor informar uma probabilidade entre 0 e 1 !!!'

In [56]:
print(probabilidade(matriz50,1))
print(probabilidade(matriz50,0.2))
print(probabilidade(matriz50,2))

[[        nan  0.76254512 -0.61496938 ...         nan         nan
  -0.13997909]
 [        nan         nan         nan ... -2.38145762         nan
   0.08566694]
 [        nan -1.04861959         nan ...         nan  0.01925729
   0.4188692 ]
 ...
 [-1.61116526         nan -1.97141765 ...         nan  0.88674976
  -0.63369228]
 [-0.0240028   0.95486082         nan ...         nan  0.83506777
   0.60240491]
 [        nan         nan  0.2705415  ...         nan         nan
  -0.4449596 ]]
[[-2.39457883  2.14372532  0.54065745 ... -0.04652025 -0.81424004
   0.86937641]
 [-0.32797832 -1.35232317 -0.64116307 ...  0.09241577 -0.4791611
   1.08944342]
 [-1.79070674  0.35042114 -0.0801644  ... -0.09572213  1.01944391
   1.52024149]
 ...
 [ 0.19965483 -0.04187994  0.1392593  ... -0.09486388  2.42722775
   0.53062895]
 [ 0.97628298  2.59830892 -0.2213427  ... -0.07842822  2.30497025
   1.8265061 ]
 [-1.37144262 -1.23918213  1.31067399 ... -1.31076143 -1.91762731
   0.64085017]]
Por favor informa

C:\Users\gfsilva\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in log
  """


21 - Crie dois arrays de 30 elementos contendo números aleatórios entre 1 e 3. Utilize os dois arrays  para derivar um novo array contendo uma comparação entre os valores de forma a indicar True caso elementos em uma mesma posição apresentam o mesmo valor e False caso contrário. Dica: não é necessário utilizar uma estrutura de repetição.

Exemplo.:

*inputs*:

array([1,3,2])

array([1,2,2])

*output*:

array([True, False, True])

In [57]:
# Insira a resposta abaixo.
a1 = np.random.randint(1,4,30)
a2 = np.random.randint(1,4,30)
print(a2)

[2 3 3 2 2 1 1 3 1 2 2 1 3 3 1 2 2 1 3 1 2 1 3 1 3 3 2 2 3 3]


22 - Compare os dois arrays acima de forma a retornar de uma única só vez um valor booleando indicando se todos os valores contidos em ambos os objetos são iguais.

In [58]:
# Insira a resposta abaixo.
#primeiro caso
print(a1 == a2)

[ True  True  True  True False False False  True  True False  True  True
 False False False False  True False  True False  True  True  True False
 False  True False False False False]


23 - Realize os seguintes procedimentos:

1. Crie um array com formato 5x5 contendo somente valores verdadeiros. 
2. Dado que se conhece o número de linhas e colunas do array, selecione aleatoriamente trẽs coordenadas (pode haver repetição de coordenadas) e as transforme em False.
3. Crie um array de dimensionalidade 5x5 a partir de um intervalo com valores de 0 até 24.
4. Utilize o array booleano para indexar o array criado no passo anterior.

In [61]:
# Insira a resposta abaixo.

# Passo 1
a = np.ones((5,5),dtype=bool)
# print(a)

# Passo 2
lin, col = np.shape(a)
for i in range(3):
  a[np.random.randint(0,lin),np.random.randint(0,col)] = False
print(a)

# Passo 3
b = np.array(range(25)).reshape(5,5)
print(b)

# Passo 4


[[ True  True False  True  True]
 [ True  True  True  True  True]
 [False  True  True  True  True]
 [ True False  True  True  True]
 [ True  True  True  True  True]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
